Remove the instruction to upgrade pip
Since pip is installed as an operating system package it now results in
the following error when trying to upgrade it directly:

Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.